import React from 'react'
import Meta from '../components/Meta.jsx'
import PageHero from '../components/PageHero.jsx'

const EMAIL='hello@khidevs.com'
const legal={
  privacy:{title:'Privacy policy',meta:'Privacy Policy — KHIDevs',description:'KHIDevs privacy policy for website visitors and project inquiries.',index:'LEGAL / PRIVACY',lead:'How KHIDevs handles information submitted through this website.',sections:[['Information we collect','When you contact KHIDevs, we may receive your name, company, email address, phone number, project details, budget range, timeline and any links or information you choose to provide.'],['How we use it','We use inquiry information to understand your request, communicate with you, prepare proposals, deliver requested services and maintain project records where a commercial relationship is established.'],['Cookies and analytics','Essential storage may be used for site preferences such as cookie consent and theme. Optional analytics should only be enabled where configured and consented to.'],['Sharing','We do not sell personal information. Information may be shared with service providers only when reasonably required to operate the website, communicate with you or deliver contracted work.'],['Retention and security','We retain information only as long as reasonably necessary for inquiries, projects, legal obligations and business records. No internet service can guarantee absolute security, but reasonable safeguards should be used.'],['Your choices','You may request access, correction or deletion of information you submitted, subject to legal and contractual retention requirements.']]},
  terms:{title:'Terms of use',meta:'Terms of Use — KHIDevs',description:'Terms governing the use of the KHIDevs website.',index:'LEGAL / TERMS',lead:'General terms for using the KHIDevs website. Project work is governed by the applicable proposal or agreement.',sections:[['Website use','This website provides general information about KHIDevs capabilities. You may not misuse the site, attempt unauthorized access, disrupt its operation or use its content unlawfully.'],['Project information','Website content is not a binding quote, guarantee or statement that a particular technology is appropriate for every project. Scope, timing, pricing, ownership, support and deliverables should be defined in a project-specific agreement.'],['Portfolio and examples','Concept and internal projects are labeled accordingly. Any future client case studies should only be published with appropriate permission and supported claims.'],['Intellectual property','Unless otherwise stated, the KHIDevs website design, copy and original site materials are owned by KHIDevs or used with permission.'],['Third-party services','Projects may rely on third-party platforms, APIs, hosting providers or software. Their availability and terms are controlled by their respective providers.']]},
  cookies:{title:'Cookie policy',meta:'Cookie Policy — KHIDevs',description:'KHIDevs cookie and local storage policy.',index:'LEGAL / COOKIES',lead:'A simple explanation of site preferences and optional analytics.',sections:[['Essential storage','The website may use local browser storage for preferences such as light/dark theme and cookie choices. The React local preview may also store test contact submissions only in your own browser.'],['Optional analytics','This source package does not include a third-party analytics tracker by default. If analytics or advertising tools are added later, they should be configured in accordance with applicable consent and privacy requirements.'],['Managing preferences','You can clear browser storage and cookies using your browser settings. Doing so may reset theme and consent preferences.']]}
}
export default function Legal({type}){const p=legal[type]||legal.privacy;return <>
  <Meta title={p.meta} description={p.description} path={`/legal/${type}/`}/><PageHero eyebrow="LEGAL" title={p.title} lead={p.lead} index={p.index}/><section className="section"><div className="shell legal-copy"><p><strong>Last updated:</strong> September 2026</p>{p.sections.map(([h,c])=><React.Fragment key={h}><h2>{h}</h2><p>{c}</p></React.Fragment>)}<h2>Contact</h2><p>Questions can be sent to <a href={`mailto:${EMAIL}`}>{EMAIL}</a>.</p></div></section>
</>}
